### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by jsina** [fortunaphantom/betby-integration#1]
I'm wondering if these APIs are related to https://betby.com or not.

**Comment by fortunaphantom** [comment]
Hello @jsina 
Can you tell me why?

**Comment by jsina** [comment]
Hey @fortunaphantom, 
I was looking for the APIs related to the Betby and I came across your GitHub repo. that's why I was asking for.

**Comment by fortunaphantom** [comment]
Correct @jsina

**Comment by jsina** [comment]
Great! I'll review your code. Since I don't have access to the API keys and related documents yet, could you let me know how much effort you spent on this repo so far?

**Comment by fortunaphantom** [comment]
Feel free to contact me at telegram: asod0000
